name: Build and Deploy to S3

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Patch libsignal (Linux/macOS)
        if: runner.os != 'Windows'
        run: cp -R docs/libsignal/. node_modules/libsignal/src/

      - name: Patch libsignal (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Copy-Item -Path docs\libsignal\* -Destination node_modules\libsignal\src -Recurse -Force

      - name: Create .env.production file
        run: echo "MAIN_VITE_API_URL=${{ secrets.MAIN_VITE_API_URL }}" > .env.production

      - name: Build Electron app (${{ matrix.os }})
        run: npm run build:${{ matrix.platform }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync builds to S3
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/releases --follow-symlinks
